### ISSUE TITLE
Too many files

### ISSUE THREAD

**Issue by barryvdh** [thephpleague/glide#256]
When there is directory with a large amount of files, it cannot create the file anymore. Related issue (I think) is this: https://github.com/thephpleague/flysystem/issues/932

It probably checks if the file already exists, but returns an incorrect result.

Stacktrace:
```
[2019-02-20 12:01:23] production.ERROR: League\Flysystem\Exception: Impossible to create the root directory "storage/app/glide/rapports/components/5c3ec63b424d2a18a29e9d6d90e60469_190359271300_5a84bdeb6912890f1cd8_48.jpg". in vendor/league/flysystem/src/Adapter/Local.php:106
Stack trace:
#0 vendor/league/flysystem/src/Adapter/Local.php(127): League\Flysystem\Adapter\Local->ensureDirectory('/home/app/domai...')
#1 vendor/league/flysystem/src/Filesystem.php(68): League\Flysystem\Adapter\Local->write('rapports/compon...', '\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x00\x00...', Object(League\Flysystem\Config))
#2 vendor/league/glide/src/Server.php(528): League\Flysystem\Filesystem->write('rapports/compon...', '\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x00\x00...')
#3 vendor/league/glide/src/Server.php(430): League\Glide\Server->makeImage('rapports/compon...', Array)
```

Not sure if this is fixable in Glide (temp solution is to just clear the cache..)

**Comment by tgalopin** [comment]
It seems to be a problem on Flysystem or even on the filesystem itself, not really on Glide. Nothing Glide can do I think.
